![logo](https://xccelerate.co/static/logo@3x-45da759fdee2af1d7e8b7cc2c3e8e73e-2c425.png)

### Day 2 Exercise - Numpy

import numpy

1) Create a null vector of size 12

In [1]:
import numpy as np
zero_vec = np.zeros(12)
print(zero_vec)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


2) Reshape the null vector to 3d array

In [2]:
zero_vec.reshape(3,2,2)

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

3) Create a 4x4 identity matrix

In [3]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

4) Create a 5x5 matrix with random integers, find min and max values

In [4]:
matrix = np.random.randint(20,size=(5,5))
print(matrix)
print('max: ', np.max(matrix))
print('min: ', np.min(matrix))

[[ 6  5 13  4 14]
 [ 4 13 13  5  7]
 [ 5  2  6 10  4]
 [ 8 16 12  0  8]
 [ 2 16  5  4 11]]
max:  16
min:  0


5) Create a 2d array with 1 on the borders and 0 on the insides

In [5]:
matrix = np.zeros((5,5))
matrix[0:1,] = 1
matrix[:,0] = 1
matrix[4:,:] = 1
matrix[:,4:5] = 1
matrix

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

6) Create a random vector of size 10 and find the mean

In [6]:
np.mean(np.random.randint(10,size=10))

5.3

7) Create a 5x5 matrix with row values 1 to 5

In [7]:
mat = np.zeros((5,5))
mat = mat + np.arange(1,6)
mat

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

8) Multiply a 5x3 matrix with a 3x2 matrix

In [8]:
mat1 = np.random.randint(20, size=(5,3))
mat2 = np.random.randint(10, size=(3,2))
np.matmul(mat1, mat2)

array([[228, 128],
       [261, 140],
       [289, 180],
       [321, 192],
       [122,  88]])

9) Create the following matrix
```python
array([[ 0.01,  0.02,  0.03,  0.04,  0.05,  0.06,  0.07,  0.08,  0.09,  0.1 ],
       [ 0.11,  0.12,  0.13,  0.14,  0.15,  0.16,  0.17,  0.18,  0.19,  0.2 ],
       [ 0.21,  0.22,  0.23,  0.24,  0.25,  0.26,  0.27,  0.28,  0.29,  0.3 ],
       [ 0.31,  0.32,  0.33,  0.34,  0.35,  0.36,  0.37,  0.38,  0.39,  0.4 ],
       [ 0.41,  0.42,  0.43,  0.44,  0.45,  0.46,  0.47,  0.48,  0.49,  0.5 ],
       [ 0.51,  0.52,  0.53,  0.54,  0.55,  0.56,  0.57,  0.58,  0.59,  0.6 ],
       [ 0.61,  0.62,  0.63,  0.64,  0.65,  0.66,  0.67,  0.68,  0.69,  0.7 ],
       [ 0.71,  0.72,  0.73,  0.74,  0.75,  0.76,  0.77,  0.78,  0.79,  0.8 ],
       [ 0.81,  0.82,  0.83,  0.84,  0.85,  0.86,  0.87,  0.88,  0.89,  0.9 ],
       [ 0.91,  0.92,  0.93,  0.94,  0.95,  0.96,  0.97,  0.98,  0.99,  1.  ]])
```

In [9]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

10) From the following matrix
```python
array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])
```
Change all the values in the middle column to 0

In [10]:
mat = np.arange(1,26).reshape(5,5)
mat[:, 2:3] = 0
print(mat)

[[ 1  2  0  4  5]
 [ 6  7  0  9 10]
 [11 12  0 14 15]
 [16 17  0 19 20]
 [21 22  0 24 25]]


11) From question 10 matrix, extract the fourth column

In [11]:
mat[:,3:4]

array([[ 4],
       [ 9],
       [14],
       [19],
       [24]])

12) From question 10 matrix switch the first and last row

In [12]:
mat[[-1,0]] = mat[[0, -1]]
mat


array([[21, 22,  0, 24, 25],
       [ 6,  7,  0,  9, 10],
       [11, 12,  0, 14, 15],
       [16, 17,  0, 19, 20],
       [ 1,  2,  0,  4,  5]])

13) From question 10 matrix find the sum of all the columns

In [13]:
np.sum(mat,axis=0)

array([55, 60,  0, 70, 75])

14) Create a random vector size 10 and replace the min value with the max value

In [14]:
matrix = np.random.randint(20,size=10)
print(matrix)
matrix[matrix.argmin()] = matrix[matrix.argmax()]
print(matrix)

[14  1 16  7 14 12  0 15 14  8]
[14  1 16  7 14 12 16 15 14  8]


15) How to find common values between two arrays?

In [15]:
arr1 = np.random.randint(1,31,10)
arr2 = np.random.randint(1,31,10)
np.intersect1d(arr1,arr2)

array([18, 29])

16) Normalize a 5x5 random matrix

In [16]:
matrix = np.random.randint(21,size=(5,5))
m_max = matrix.max()
m_min = matrix.min()
matrix = (matrix - m_min)/(m_max - m_min)
matrix

array([[0.85, 0.75, 0.4 , 0.  , 0.05],
       [0.7 , 0.8 , 0.8 , 0.2 , 0.25],
       [1.  , 0.85, 0.5 , 0.05, 0.75],
       [0.5 , 0.8 , 0.5 , 0.35, 0.25],
       [0.85, 0.65, 0.65, 0.15, 0.15]])

17) Create a random vector of size 20 and sort in descending order

In [17]:
mat = np.random.randint(100,size=20)
sorted(mat, reverse=True)

[99, 96, 94, 93, 73, 70, 58, 53, 52, 51, 26, 21, 16, 14, 14, 13, 9, 8, 5, 4]

18) How to convert a float array in an integer in place?

In [18]:
zeros = np.zeros(10)
print(zeros)
print(zeros.astype(int))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0 0 0 0 0 0 0 0 0 0]


19) From a vector with random integers filter out values that have mod 0

In [19]:
matrix = np.random.randint(20, size=10)
matrix[matrix % 2 == 0]

array([10,  6, 18, 10,  8,  6])

20) Create a 3x3 matrix where all values are evenly spaced

In [20]:
np.linspace(1,100, num=9)

array([  1.   ,  13.375,  25.75 ,  38.125,  50.5  ,  62.875,  75.25 ,
        87.625, 100.   ])

For more numpy exercise see [numpy exercises](https://github.com/rougier/numpy-100) 

*NOTE: in programming there many methods to get the same answer, good code is commented code and  runs at optimal speed